INSERT INTO STATUS (id, name) VALUES (1, 'ACTIVE');
INSERT INTO STATUS (id, name) VALUES (2, 'INACTIVE');
INSERT INTO STATUS (id, name) VALUES (3, 'PENDING');
INSERT INTO STATUS (id, name) VALUES (4, 'SUSPENDED');